### ISSUE TITLE
errorrr

### ISSUE THREAD

**Issue by ABHI01OP** [ultrasecurity/Storm-Breaker#114]
Traceback (most recent call last):
  File "/mnt/c/Users/abhir/limux/Storm-Breaker/Storm-breaker.py", line 36, in <module>
    banner.banner()
  File "/mnt/c/Users/abhir/limux/Storm-Breaker/modules/banner.py", line 10, in banner
    Popen('neofetch')
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'neofetch'

**Comment by ABHI01OP** [comment]
pls fixx
