### ISSUE TITLE
Installed multiple times and in different locations and same issue

### ISSUE THREAD

**Issue by wizhardhacker1** [ultrasecurity/Storm-Breaker#118]
Traceback (most recent call last):                                                                                             
  File "/usr/local/lib/python3.9/dist-packages/pyngrok/installer.py", line 94, in install_ngrok                                
    download_path = _download_file(url, **kwargs)                                                                              
  File "/usr/local/lib/python3.9/dist-packages/pyngrok/installer.py", line 232, in _download_file                              
    with open(download_path, "wb") as f:                                                                                       
PermissionError: [Errno 13] Permission denied: '/tmp/ngrok-stable-linux-amd64.zip'                                             
                                                                                                                               
During handling of the above exception, another exception occurred:                                                            
                                                                                                                               
Traceback (most recent call last):                                                                                             
  File "/home/Storm-Breaker/Storm-Breaker.py", line 46, in <module>                                                            
    localhost.webcham()                                                                                                        
  File "/home/Storm-Breaker/modules/localhost.py", line 74, in webcham                                                         
    a = ngrok.connect(4545,"http",auth_token=token)                                                                            
  File "/usr/local/lib/python3.9/dist-packages/pyngrok/ngrok.py", line 251, in connect                                         
    api_url = get_ngrok_process(pyngrok_config).api_url                                                                        
  File "/usr/local/lib/python3.9/dist-packages/pyngrok/ngrok.py", line 160, in get_ngrok_process                               
    install_ngrok(pyngrok_config)                                                                                              
  File "/usr/local/lib/python3.9/dist-packages/pyngrok/ngrok.py", line 98, in install_ngrok                                    
    installer.install_ngrok(pyngrok_config.ngrok_path)                                                                         
  File "/usr/local/lib/python3.9/dist-packages/pyngrok/installer.py", line 98, in install_ngrok                                
    raise PyngrokNgrokInstallError("An error occurred while downloading ngrok from {}: {}".format(url, e))                     
pyngrok.exception.PyngrokNgrokInstallError: An error occurred while downloading ngrok from https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip: [Errno 13] Permission denied: '/tmp/ngrok-stable-linux-amd64.zip'

**Comment by wizhardhacker1** [comment]
fix is to delete the /tmp/ngrok-stable-linux-amd64.zip'
