### ISSUE TITLE
ModuleNotFoundError: No module named 'pyngrok'

### ISSUE THREAD

**Issue by Spellingis** [ultrasecurity/Storm-Breaker#132]
┌──(Davis㉿)-[~/Storm-Breaker]
└─$ sudo python3 Storm-Breaker.py
Traceback (most recent call last):
  File "/home/handa/Storm-Breaker/Storm-Breaker.py", line 7, in <module>
    from modules import localhost
  File "/home/handa/Storm-Breaker/modules/localhost.py", line 1, in <module>
    from pyngrok import ngrok
ModuleNotFoundError: No module named 'pyngrok'
-----------------------------------------------------------------------------------------------
I am using Kali Linux WSL2 on windows 10 
Thank you!

**Comment by uidops** [comment]
install pyngrok
