### ISSUE TITLE
Storm-Breaker not executing hence error is shown

### ISSUE THREAD

**Issue by HariKrishna100** [ultrasecurity/Storm-Breaker#19]
I ran sudo python3 Storm-Breaker.py then
Traceback (most recent call last):
File "/home/hunter/Storm-Breaker/Storm-Breaker.py", line 6, in 
from modules import banner
File "/home/hunter/Storm-Breaker/modules/banner.py", line 2, in 
from colorama import Fore
ModuleNotFoundError: No module named 'colorama'

THIS IS THE ISSUE IN THE CODE PLEASE SOLVE THE ISSUE ASAP AND HELP ME HOW TO FIX THE ISSUE
@ultrasecurity

**Comment by Mrli-hong** [comment]
I have the same issues

**Comment by HariKrishna100** [comment]
Finally people replied but this developers they aren’t responding

**Comment by KrishnaSharma000** [comment]
Ultimate solution:-
Copy and paste these new  commands  same as given below:-
 sudo  git clone https://github.com/ultrasecurity/Storm-Breaker
 cd Storm-Breaker
 sudo bash install.sh
 sudo python3 -m pip install -r requirments.txt
 sudo python3 Storm-Breaker.py

**Comment by RadicalUser** [comment]
> python3 Storm-Breaker.py

not working

**Comment by shivanshdixit245-ai** [comment]
First type - chmod 777 storm-web/log/
then run python file in root like sudo python3 st.py
