### ISSUE TITLE
error execting sudo python3 st.py

### ISSUE THREAD

**Issue by Mission396** [ultrasecurity/Storm-Breaker#198]
Traceback (most recent call last):
  File "/Users/butidoubata/Storm-Breaker/st.py", line 6, in <module>
    check.check_update()
  File "/Users/butidoubata/Storm-Breaker/modules/check.py", line 38, in check_update
    http_json = json.loads(http)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 4 (char 3)

**Comment by pinguiman** [comment]
im having the same issue

**Comment by joshkar** [comment]
Hello. The tool has been updated. Please update it
