### ISSUE TITLE
Colorama not found

### ISSUE THREAD

**Issue by Autobot4123** [ultrasecurity/Storm-Breaker#20]
Traceback (most recent call last):
File "/home/hunter/Storm-Breaker/Storm-Breaker.py", line 6, in
from modules import banner
File "/home/hunter/Storm-Breaker/modules/banner.py", line 2, in
from colorama import Fore
ModuleNotFoundError: No module named 'colorama'

THIS IS THE ISSUE IN THE CODE PLEASE SOLVE THE ISSUE ASAP AND HELP ME HOW TO FIX THE ISSUE
@ultrasecurity

**Comment by Mrli-hong** [comment]
Traceback (most recent call last):
  File "/home/kali/Storm-Breaker/Storm-Breaker.py", line 36, in <module>
    banner.banner()
  File "/home/kali/Storm-Breaker/modules/banner.py", line 10, in banner
    Popen('neofetch')
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'neofetch'
