### ISSUE TITLE
Storm-Breaker not executing 

### ISSUE THREAD

**Issue by HariKrishna100** [ultrasecurity/Storm-Breaker#23]
Traceback (most recent call last):
File "/home/hunter/Storm-Breaker/Storm-Breaker.py", line 6, in
from modules import banner
File "/home/hunter/Storm-Breaker/modules/banner.py", line 2, in
from colorama import Fore
ModuleNotFoundError: No module named 'colorama'

THIS IS THE ISSUE IN THE CODE PLEASE SOLVE THE ISSUE ASAP AND HELP ME HOW TO FIX THE ISSUE
@ultrasecurity

**Comment by spyfox46** [comment]
same problems after couple tries with my phone and web browser
