### ISSUE TITLE
python3 st.py not working

### ISSUE THREAD

**Issue by Aryan2139** [ultrasecurity/Storm-Breaker#231]
Plzz help 
It's showing this again and again
Here's the error
( ) ( * ( ) (
)\ ) * ) ( /( )\ ) (            (   )\ )       (       ( /(       )\ ) (()/( ) /( )()) (()/( )))( ( )\ (()/( ( )\ )()) ( (()/(
/())( )())(()\ /())()\ ___ )(() /()))\ (((()( |(()\ )\ /())
()) ((()) (() ()) (()(()||(() ()) (() )\ _ )\ |_ (()(() ())
/ _|| | / _ \ | _ \ | / | | _ )| _ | __|()()| |/ / | _|| _ \
_ \ | | | () || / | |/| | | _ | /| | / _ \ ' < | | | /
|/ || _/ ||\ || || |/||||// _\ |_\ ||||_\

Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 174, in _new_conn
conn = connection.create_connection(
File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 96, in create_connection
raise err
File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 86, in create_connection
sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 704, in urlopen
httplib_response = self._make_request(
File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
self._validate_conn(conn)
File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1045, in _validate_conn
conn.connect()
File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 358, in connect
self.sock = conn = self._new_conn()
File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 186, in _new_conn
raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f05990b74c0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/requests/adapters.py", line 489, in send
resp = conn.urlopen(
File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 788, in urlopen
retries = retries.increment(
File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 592, in increment
raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /ultrasecurity/Storm-Breaker/main/Settings.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f05990b74c0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/root/Storm-Breaker/st.py", line 6, in
check.check_update()
File "/root/Storm-Breaker/modules/check.py", line 36, in check_update
http = requests.get("[https://raw.githubusercontent.com/ultrasecurity/Storm-Breaker/main/Settings.json").text](https://raw.githubusercontent.com/ultrasecurity/Storm-Breaker/main/Settings.json%22).text)
File "/usr/lib/python3/dist-packages/requests/api.py", line 73, in get
return request("get", url, params=params, **kwargs)
File "/usr/lib/python3/dist-packages/requests/api.py", line 59, in request
return session.request(method=method, url=url, **kwargs)
File "/usr/lib/python3/dist-packages/requests/sessions.py", line 587, in request
resp = self.send(prep, **send_kwargs)
File "/usr/lib/python3/dist-packages/requests/sessions.py", line 701, in send
r = adapter.send(request, **kwargs)
File "/usr/lib/python3/dist-packages/requests/adapters.py", line 565, in send
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /ultrasecurity/Storm-Breaker/main/Settings.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f05990b74c0>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by Msa360** [comment]
It seems you have a problem with making tcp connnections. Is your computer normally able to connect to websites? Or if you are running it on a vm, is your vm normally working well when going to websites? Some VM's like virtual box might need special configuration to allow internet access.

**Comment by Aryan2139** [comment]
> It seems you have a problem with making tcp connnections. Is your computer normally able to connect to websites? Or if you are running it on a vm, is your vm normally working well when going to websites? Some VM's like virtual box might need special configuration to allow internet access.

Yes I can surfe on internet very well and there is no problem with that

**Comment by Msa360** [comment]
Try to run this python program on your computer:
```python3
import requests
response = requests.get("https://raw.githubusercontent.com/ultrasecurity/Storm-Breaker/main/Settings.json")
print(response.text)
```
you should see something like this:
`{"pid": [], "is_start": false, "version": 3.0}`

If this doesn't work, it means you have a problem with the requests package (maybe it is not up to date) so you should uninstall it and reinstall it. If you do this make sure you don't have other personal projects relying on your current version of requests (normally you should be good).
To uninstall and reinstall with pip run these commands in terminal:
```bash
pip uninstall requests
pip install requests
```

**Comment by kaligithub11** [comment]
python3 st.py wont be working rather it shows no such file or directory exist
python3 file cant be opening what else i can inorder to open python3
and moreover i got this ( ) ( * ( ) (
)\ ) * ) ( /( )\ ) ( ( )\ ) ( ( /( )\ ) (()/( ) /( )()) (()/( )))( ( )\ (()/( ( )\ )()) ( (()/(
/())( )())(()\ /())()\ ___ )(() /()))\ (((()( |(()\ )\ /())
()) ((()) (() ()) (()(()||(() ()) (() )\ _ )\ |_ (()(() ())
/ _|| | / _ \ | _ \ | / | | _ )| _ | __|()()| |/ / | _|| _
_ \ | | | () || / | |/| | | _ | /| | / _ \ ' < | | | /
|/ || / ||\ || || |/||||// \ |\ ||||\ i tried several times i dont how i can make it work
im hoping u can give brief info about it

**Comment by Msa360** [comment]
@kaligithub11 did you run "python3 st.py" inside the storm-breaker directory? Maybe try "sudo python3 st.py"

**Comment by kaligithub11** [comment]
I would have tried several times still i got an error like this no such file or directory

**Comment by kaligithub11** [comment]
Inside the storm breaker there is no file exit with python3 st.py there is only one file that exists as st.py

**Comment by Msa360** [comment]
it's normal that there is no file named "python3 st.py", python3 is what you need to type to run python and st.py is the name of the file you want to run.

**Comment by kaligithub11** [comment]
everytime i enter python3 st.py it shows traceback error

**Comment by kaligithub11** [comment]
python3 st.py
python3: can't open file '/home/kali/st.py': [Errno 2] No such file or directory

**Comment by Msa360** [comment]
It's normal, you need to first be in the Storm-Breaker folder. So first run `cd Storm-Breaker` and then `python3 st.py`.

**Comment by kaligithub11** [comment]
such file or directory exist
python3 file cant be opening what else i can inorder to open python3
and moreover i got this ( ) ( * ( ) (
)\ ) * ) ( /( )\ ) ( ( )\ ) ( ( /( )\ ) (()/( ) /( )()) (()/( )))( ( )\ (()/( ( )\ )()) ( (()/(
/())( )())(()\ /())()\ ___ )(() /()))\ (((()( |(()\ )\ /())
()) ((()) (() ()) (()(()||(() ()) (() )\ _ )\ |_ (()(() ())
/ _|| | / _ \ | _ \ | / | | _ )| _ | __|()()| |/ / | _|| _
_ \ | | | () || / | |/| | | _ | /| | / _ \ ' < | | | /
|/ || / ||\ || || |/||||// \ |\ ||||\ i tried several times i dont how i can make it work
im hoping u can give brief info about it

it should be not working properly

**Comment by Scbisui** [comment]
I solved it.
Try to delete or comment out the update() in st.py.
