### ISSUE TITLE
invalid requirement

### ISSUE THREAD

**Issue by kaligithub420** [ultrasecurity/Storm-Breaker#270]
Hit:1 http://kali.download/kali kali-rolling InRelease     
Ign:2 https://repo.protonvpn.com/debian stable InRelease
Ign:2 https://repo.protonvpn.com/debian stable InRelease
Ign:2 https://repo.protonvpn.com/debian stable InRelease
Err:2 https://repo.protonvpn.com/debian stable InRelease
  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 104.26.5.35 443]
WARNING:root:cannot read /var/lib/command-not-found/commands.db.metadata: Expecting value: line 1 column 1 (char 0)
E: LZ4F: /var/lib/apt/lists/http.kali.org_kali_dists_kali-rolling_main_Contents-amd64.lz4 Unexpected end of file
E: LZ4F: /var/lib/apt/lists/http.kali.org_kali_dists_kali-rolling_main_Contents-amd64.lz4 Read error (18446744073709551615: ERROR_GENERIC)
Traceback (most recent call last):
  File "/usr/lib/cnf-update-db", line 32, in <module>
    col.create(db)
  File "/usr/share/command-not-found/CommandNotFound/db/creator.py", line 96, in create
    self._fill_commands(con)
  File "/usr/share/command-not-found/CommandNotFound/db/creator.py", line 145, in _fill_commands
    raise subprocess.CalledProcessError(returncode=sub.returncode,
subprocess.CalledProcessError: Command '/usr/lib/apt/apt-helper cat-file /var/lib/apt/lists/http.kali.org_kali_dists_kali-rolling_main_Contents-amd64.lz4' returned non-zero exit status 100.
Reading package lists... Done
W: Failed to fetch https://repo.protonvpn.com/debian/dists/stable/InRelease  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 104.26.5.35 443]
W: Some index files failed to download. They have been ignored, or old ones used instead.
E: Problem executing scripts APT::Update::Post-Invoke-Success 'if /usr/bin/test -w /var/lib/command-not-found/ -a -e /usr/lib/cnf-update-db; then /usr/lib/cnf-update-db > /dev/null; fi'
E: Sub-process returned an error code
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3 is already the newest version (3.11.2-1+b1).
python3-pip is already the newest version (23.1.2+dfsg-2).
php is already the newest version (2:8.2+93).
0 upgraded, 0 newly installed, 0 to remove and 367 not upgraded.
ERROR: Invalid requirement: './requirements.txt'
Hint: It looks like a path. The path does exist. The argument you provided (./requirements.txt) appears to be a requirements file. If that is the case, use the '-r' flag to install the packages specified within it.                
An error occurred! seems pip doesn't work.

**Comment by Eleanya-David** [comment]
bro bro please reply
lets link up
im having this same issue

**Comment by IamUsike** [comment]
@Eleanya-David DId you resolve it please help
