### ISSUE TITLE
requirements

### ISSUE THREAD

**Issue by halloichbincool123** [ultrasecurity/Storm-Breaker#276]
Hi i nned help installing the tool every time i try to bash install.sh it shows:

Hit:1 http://packages.microsoft.com/repos/code stable InRelease
Hit:2 https://repo.protonvpn.com/debian stable InRelease                                     
Hit:3 http://repository.spotify.com stable InRelease                                         
Hit:4 http://ftp.halifax.rwth-aachen.de/kali kali-rolling InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3 is already the newest version (3.11.2-1+b1).
python3-pip is already the newest version (23.1.2+dfsg-2).
php is already the newest version (2:8.2+93).
The following packages were automatically installed and are no longer required:
  libixml10 libmujs2 libupnp13 libyara9 python3-pytz-deprecation-shim python3-texttable tftp
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 202 not upgraded.
ERROR: Invalid requirement: './requirements.txt'
Hint: It looks like a path. The path does exist. The argument you provided (./requirements.txt) appears to be a requirements file. If that is the case, use the '-r' flag to install the packages specified within it.
An error occurred! seems pip doesn't work.

**Comment by z502wa** [comment]
cd Storm-Breaker 
cd modules/   
nano check.py  

comment last part like this 

`def check_update():
    pass
    # http = requests.get("https://raw.githubusercontent.com/ultrasecurity/Storm-Breaker/main/Settings.json").text
    # http_json = json.loads(http)

    # with open("storm-web/Settings.json", "r") as jsonFile:
    #     data = json.load(jsonFile)
    #     if data['version'] < http_json['version']:
    #         exit("Please Update Tool") `

then 
sudo python3 st.py 
it will work

**Comment by z502wa** [comment]
> def check_update():
    pass
    # http = requests.get("https://raw.githubusercontent.com/ultrasecurity/Storm-Breaker/main/Settings.json").text
    # http_json = json.loads(http)

    # with open("storm-web/Settings.json", "r") as jsonFile:
    #     data = json.load(jsonFile)
    #     if data['version'] < http_json['version']:
    #         exit("Please Update Tool")

**Comment by z502wa** [comment]
`def check_update():
    pass
    # http = requests.get("https://raw.githubusercontent.com/ultrasecurity/Storm-Breaker/main/Settings.json").text
    # http_json = json.loads(http)

    # with open("storm-web/Settings.json", "r") as jsonFile:
    #     data = json.load(jsonFile)
    #     if data['version'] < http_json['version']:
    #         exit("Please Update Tool")`

**Comment by z502wa** [comment]
cd Storm-Breaker 
cd modules/   
nano check.py  

edit the last part like this 

```
def check_update():
    pass
    # http = requests.get("https://raw.githubusercontent.com/ultrasecurity/Storm-Breaker/main/Settings.json").text
    # http_json = json.loads(http)

    # with open("storm-web/Settings.json", "r") as jsonFile:
    #     data = json.load(jsonFile)
    #     if data['version'] < http_json['version']:
    #         exit("Please Update Tool") 
```
save it
then 
sudo python3 st.py 
it will work

**Comment by mohit6350** [comment]
Thanks z502wa. It worked.❤

**Comment by dileep-2002** [comment]
It doesn't work for me

**Comment by IamUsike** [comment]
#277 
I tried and i'm getting the following error Traceback (most recent call last):
  File "/home/kali/additional/Storm-Breaker/st.py", line 1, in <module>
    from modules import check
  File "/home/kali/additional/Storm-Breaker/modules/check.py", line 32
    def check_update():
                       ^
IndentationError: unindent does not match any outer indentation level

**Comment by zwishz** [comment]
> cd Storm-Breaker cd modules/ nano check.py
> 
> edit the last part like this
> 
> ```
> def check_update():
>     pass
>     # http = requests.get("https://raw.githubusercontent.com/ultrasecurity/Storm-Breaker/main/Settings.json").text
>     # http_json = json.loads(http)
> 
>     # with open("storm-web/Settings.json", "r") as jsonFile:
>     #     data = json.load(jsonFile)
>     #     if data['version'] < http_json['version']:
>     #         exit("Please Update Tool") 
> ```
> 
> save it then sudo python3 st.py it will work

How do i edit in terminal?

**Comment by zwishz** [comment]
> cd Storm-Breaker cd modules/ nano check.py
> 
> edit the last part like this
> 
> ```
> def check_update():
>     pass
>     # http = requests.get("https://raw.githubusercontent.com/ultrasecurity/Storm-Breaker/main/Settings.json").text
>     # http_json = json.loads(http)
> 
>     # with open("storm-web/Settings.json", "r") as jsonFile:
>     #     data = json.load(jsonFile)
>     #     if data['version'] < http_json['version']:
>     #         exit("Please Update Tool") 
> ```
> 
> save it then sudo python3 st.py it will work

how to save?

**Comment by zwishz** [comment]
> cd Storm-Breaker cd modules/ nano check.py
> 
> edit the last part like this
> 
> ```
> def check_update():
>     pass
>     # http = requests.get("https://raw.githubusercontent.com/ultrasecurity/Storm-Breaker/main/Settings.json").text
>     # http_json = json.loads(http)
> 
>     # with open("storm-web/Settings.json", "r") as jsonFile:
>     #     data = json.load(jsonFile)
>     #     if data['version'] < http_json['version']:
>     #         exit("Please Update Tool") 
> ```
> 
> save it then sudo python3 st.py it will work

After editing it, I'm getting this error : 

Traceback (most recent call last):
  File "/opt/Storm-Breaker/st.py", line 1, in <module>
    from modules import check
  File "/opt/Storm-Breaker/modules/check.py", line 37
    http = requests.get("https://raw.githubusercontent.com/ultrasecurity/Storm-Breaker/main/Settings.json").text
IndentationError: unexpected indent
