### ISSUE TITLE
python3 st.py is not running ERROR(101)

### ISSUE THREAD

**Issue by maggijasjuz** [ultrasecurity/Storm-Breaker#298]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 704, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1045, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f3249e00cd0>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 788, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /ultrasecurity/Storm-Breaker/main/Settings.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3249e00cd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/maira28/Storm-Breaker/st.py", line 6, in <module>
    check.check_update()
  File "/home/maira28/Storm-Breaker/modules/check.py", line 36, in check_update
    http = requests.get("https://raw.githubusercontent.com/ultrasecurity/Storm-Breaker/main/Settings.json").text
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /ultrasecurity/Storm-Breaker/main/Settings.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3249e00cd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

**Comment by aslanbekmahmud** [comment]
İ have the same issue

**Comment by shashankfzb** [comment]
I also have the same issue

**Comment by Krishna7729** [comment]
I also have same issue

**Comment by Ismaililu** [comment]
i also have the same issues

**Comment by Ismaililu** [comment]
t=2023-12-12T20:07:45-0500 lvl=warn msg="invalid tunnel configuration" pg=/api/tunnels id=da672b2f69c39fb0 err="yaml: unmarshal errors:\n  line 1: field auth_token not found in type config.HTTPv2Tunnel"
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/pyngrok/ngrok.py", line 507, in api_request
    response = urlopen(request, encoded_data, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/stormbreaker/Storm-Breaker.py", line 24, in <module>
    localhost.webcham()
  File "/home/kali/stormbreaker/modules/localhost.py", line 73, in webcham
    a = ngrok.connect(4545,"http",auth_token=token)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pyngrok/ngrok.py", line 313, in connect
    tunnel = NgrokTunnel(api_request("{}/api/tunnels".format(api_url), method="POST", data=options,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pyngrok/ngrok.py", line 528, in api_request
    raise PyngrokNgrokHTTPError("ngrok client exception, API returned {}: {}".format(status_code, response_data),
pyngrok.exception.PyngrokNgrokHTTPError: ngrok client exception, API returned 400: {"error_code":102,"status_code":400,"msg":"invalid tunnel configuration","details":{"err":"yaml: unmarshal errors:\n  line 1: field auth_token not found in type config.HTTPv2Tunnel"}}

**Comment by allset56-dev** [comment]
It looks like you are encountering an error related to ngrok and Python in your Kali Linux environment. The specific error message indicates an issue with the ngrok tunnel configuration.

Here are a few steps you can take to troubleshoot this issue:

1. Check ngrok Configuration: Ensure that you have the correct configuration for ngrok. Verify the presence of the "auth_token" field in the ngrok configuration, as it seems to be missing based on the error message.

2. Python Library: If you are using a Python library to interface with ngrok, make sure that the library is correctly configured and that you are passing the necessary parameters, such as the authentication token, when creating the ngrok tunnel.

3. API Request: The error message also mentions an API request, indicating that there might be an issue with the API request being made to ngrok. Check the API request code in your Python script to ensure that it is properly formatted and includes all required parameters.

4. Debugging: You can add print statements or logging to your Python script to output the configuration and parameters being used for the ngrok tunnel creation. This can help you identify any discrepancies or missing values.

5. ngrok Documentation: Refer to the ngrok documentation and examples to ensure that you are using the correct syntax and parameters when creating a tunnel via the ngrok API.

By carefully reviewing your ngrok configuration, Python code, and API request, you should be able to pinpoint the issue causing the "invalid tunnel configuration" error. If you need further assistance, feel free to provide more details about your specific ngrok setup and Python code.

**Comment by iamajirobamusty** [comment]
i also got the same error and what i did was to open the st.py file and comment check.check_update()
<img width="569" alt="article 4" src="https://github.com/ultrasecurity/Storm-Breaker/assets/110599927/fd4db708-ac92-421e-aac4-22b850fb5a93">

**Comment by Warhammar** [comment]
Solved problem with:
# ngrok Agent Configuration File v3
# https://ngrok.com/docs/agent/config/

# ######################################################################
# # Agent Configuration                                                #
# ######################################################################

# ----------------------------------------------------------------------
# | Version  (required)                                                |
# ----------------------------------------------------------------------

# Specifies the version of the config file to use. Valid options are 2 or 3.

version: 3

# ----------------------------------------------------------------------
# | Agent with authtoken (required)                                    |
# ----------------------------------------------------------------------

# Specifies the authentication token (authtoken) used to communicate to the
# ngrok service.
#
#  (1) You can get your default authtoken through the dashboard:
#      https://dashboard.ngrok.com/get-started/your-authtoken
#
#  (2) You can view and generate authtokens through the dashboard
#      https://dashboard.ngrok.com/tunnels/authtokens

agent:
  authtoken: 4nq9771bPxe8ctg7LKr_2ClH7Y15Zqe4bWLWF9p # example authtoken

# ----------------------------------------------------------------------
# | API Key                                                            |
# ----------------------------------------------------------------------

# The ngrok API key used to connect to the ngrok API.
#
#  (!) This is only needed when using the ngrok api command and should
#      not be confused with the authtoken.
#
#  (1) You can obtain and manage your API Keys through the dashboard:
#      https://dashboard.ngrok.com/api-keys

# api_key: 24yRd5U3DestCQapJrrVHLOqiAC_7RviwRqpd3wc9dKLujQZN

# ----------------------------------------------------------------------
# | Connect Timeout                                                    |
# ----------------------------------------------------------------------

# How long to wait when establishing an agent session connection to the
# ngrok service.
#
# Accepts duration, the default is 10s

# connect_timeout: 10s

# ----------------------------------------------------------------------
# | Console UI                                                         |
# ----------------------------------------------------------------------

# Enable or disable the console UI in the terminal.
#
# Options:
#   true   - Enable the console UI.
#   false  - Disable the console UI, use structured log format.
#   iftty  - (Default) Enable UI only if standard out is a TTY.

# console_ui: iftty

# ----------------------------------------------------------------------
# | Console UI Color                                                   |
# ----------------------------------------------------------------------

# Sets the console UI background color in the terminal.
#
# To use a color other than black, set to `transparent` and adjust your
# terminal's background.

# console_ui_color: transparent

# ----------------------------------------------------------------------
# | CRL No Verify                                                      |
# ----------------------------------------------------------------------

# Skip Certificate Revocation List (CRL) verification if set to true.
#
# Accepts a boolean. Default is `false`.

# crl_noverify: false

# ----------------------------------------------------------------------
# | DNS Resolver IPs                                                   |
# ----------------------------------------------------------------------

# List of DNS servers for resolving tunnel session DNS.
#
# Defaults to using the local system DNS servers.

# dns_resolver_ips:
#   - 1.1.1.1
#   - 8.8.8.8

# ----------------------------------------------------------------------
# | Heartbeat Interval                                                 |
# ----------------------------------------------------------------------

# How often the ngrok agent should heartbeat to the ngrok servers defined
# as a duration.
#
# Accepts a duration (e.g., 10s, 1m). The default value is `10s`.

# heartbeat_interval: 10s

# ----------------------------------------------------------------------
# | Heartbeat Tolerance                                                |
# ----------------------------------------------------------------------

# This setting defines the maximum duration to wait for a heartbeat
# response from the server before reconnecting the agent tunnel session.
#
# Accepts a duration (e.g., 10s, 1m). The default value is `15s`.

# heartbeat_tolerance: 15s

# ----------------------------------------------------------------------
# | Inspect DB Size                                                    |
# ----------------------------------------------------------------------

# This is the upper limit in bytes on memory to allocate when saving
# requests over HTTP endpoints for inspection and reply.
#
# Accepts a numeric value. The default is `0`, equivalent to 50MB.
#
#   (!) To disable inspection for all endpoints, set the value to `-1`.

# inspect_db_size: 52428800 # 50MB

# ----------------------------------------------------------------------
# | Log Level                                                          |
# ----------------------------------------------------------------------

# Sets the log detail level. Higher verbosity with each level.
#
# Allowed values:
#    crit  - Critical issues.
#    warn  - Warnings.
#   error  - Errors.
#    info  - (Default) Informational messages.
#   debug  - Detailed debugging info.

# log_level: info

# ----------------------------------------------------------------------
# | Log Format                                                         |
# ----------------------------------------------------------------------

# Specifies the format of log records.
#
# Allowed values:
#   logfmt  - (Default) Human and machine-friendly key/value pairs.
#     json  - Newline-separated JSON objects.
#     term  - Colored format for TTY; otherwise, same as logfmt.

# log_format: json

# ----------------------------------------------------------------------
# | Log                                                                |
# ----------------------------------------------------------------------

# This is the destination where ngrok should write the logs.
#
# Allowed values:
#   stdout  - write to standard out
#   stderr  - write to standard error (default)
#    false  - disable logging
#   <path>  - write log records to file path on disk

# log: /var/log/ngrok.log

# ----------------------------------------------------------------------
# | Metadata                                                           |
# ----------------------------------------------------------------------

# Custom string included in the ngrok API response for endpoints.
#
# Maximum 4096 characters.

# metadata: '{"serial": "00012xa-33rUtz9", "comment": "For customer alan@example.com"}'

# ----------------------------------------------------------------------
# | Proxy URL                                                          |
# ----------------------------------------------------------------------

# URL of an HTTP or SOCKS5 proxy for endpoint connections.
#
#   (!) ngrok will also respect the `http_proxy`, `http_proxy_env`, and `socks5_proxy`
#       environment variables.

# proxy_url: socks5://localhost:9150

# ----------------------------------------------------------------------
# | Remote Management                                                  |
# ----------------------------------------------------------------------

# Allows remote management of the ngrok agent (stop, restart, update) via
# the ngrok API or Dashboard.
#
# Defaults to `true`.

# remote_management: false

# ----------------------------------------------------------------------
# | Root CAs                                                           |
# ----------------------------------------------------------------------

# Root certificate authorities used to validate TLS connections to the
# ngrok server.
#
# Allowed values:
#    trusted - Use only the trusted certificate root for ngrok.com.
#       host - Use the root certificates trusted by the host's OS (useful for MITM proxies with DPI).
#     <path> - Path to a PEM file with additional trusted certificate authorities.

# root_cas: trusted

# ----------------------------------------------------------------------
# | Server Address                                                     |
# ----------------------------------------------------------------------

# This is the URL of the ngrok server to connect to.
#
#   (!) You should only set this value if you are using a Custom Agent
#       Ingress URL.
#
# https://ngrok.com/docs/agent/ingress/#customize-agent-ingress-address

# connect_url: tunnel.us.ingress.example.com:443

# ----------------------------------------------------------------------
# | Update Channel                                                     |
# ----------------------------------------------------------------------

# Determines the stability of builds for updates.
#
#   (!) Use `stable` for any production deployments.
#
# Allowed values:
#     stable - (Default) Production-ready builds.
#   unstable - Nightly builds; may be unstable. Not for production.
#       beta - Beta builds; may be unstable. Not for production.

# update_channel: stable

# ----------------------------------------------------------------------
# | Update Check                                                       |
# ----------------------------------------------------------------------

# Controls whether the ngrok agent checks for updates.
#
# Defaults to true.

# update_check: false

# ----------------------------------------------------------------------
# | Web Address                                                        |
# ----------------------------------------------------------------------

# Network address to bind for the local agent web interface and API.
#
# https://ngrok.com/docs/agent/web-inspection-interface/
# https://ngrok.com/docs/agent/api/

# web_addr: localhost:4040

# ----------------------------------------------------------------------
# | Web Allow Hosts                                                    |
# ----------------------------------------------------------------------

# List of allowed Host headers for requests to the local agent web
# interface and API. The port is stripped from the Host header before
# matching.
#
# Allowed formats:
#           8.8.8.8  - Matches exact IP in Host header (e.g., 8.8.8.8).
#   1:2:3:4:5:6:7:8  - Matches exact IPv6 in Host header.
#        10.0.0.0/8  - Matches any IP within a CIDR range.
#       example.com  - Matches exact hostname.
#      .example.com  - Matches subdomains (e.g., sub.example.com).
#
# The default only allows localhost-like Hosts (localhost, 127.0.0.1,
# ::1, etc.).

# web_allow_hosts:
#   - 8.8.8.8
#   - example.com

# ######################################################################
# # Endpoints Configuration                                            #
# ######################################################################

# Define individual endpoints and their configurations.
#
# Each entry under 'endpoints' represents an endpoint that can be
# started using the 'ngrok start' command:
#   https://ngrok.com/docs/agent/cli/#ngrok-start
#
# To start all endpoints at once, use:
#   ngrok start --all
#
# List of common configuration fields:
#   https://ngrok.com/docs/agent/config/v3/#common-endpoint-configuration-properties
#
# List of HTTP configuration fields:
#   https://ngrok.com/docs/agent/config/v3/#http-configuration
#
# List of TCP configuration fields:
#   https://ngrok.com/docs/agent/config/v3/#tcp-configuration
#
# List of TLS endpoint configuration fields:
#   https://ngrok.com/docs/agent/config/v3/#tls-configuration

endpoints:

  # --------------------------------------------------------------------
  # | Basic Endpoint Example                                           |
  # --------------------------------------------------------------------

  # Endpoint configuration for a website protected by basic authentication
  # with a custom host header.
  #
  # Start with after uncommenting:
  #   ngrok start example-website

  # upstream protocol allows for nuanced protocol versions: http1, http2 (default http1)

  # - name: example-website
  #   metadata: foo123
  #   url: example-website.ngrok.app
  #   upstream:
  #     url: 8080
  #     protocol: http1

  # --------------------------------------------------------------------
  # | End-to-End TLS Endpoint                                          |
  # --------------------------------------------------------------------

  # Endpoint configuration for end-to-end TLS connections.
  #
  # Start with after uncommenting:
  #   ngrok start example-e2e-tls

  # - name: example-e2e-tls
  #   url: "tls://myapp.example.com"
  #   upstream:
  #     url: 9000

  # --------------------------------------------------------------------
  # | Endpoint with Traffic Policy                                     |
  # --------------------------------------------------------------------

  # Endpoint with a Traffic Policy.
  #
  # Start with after uncommenting:
  #   ngrok start example-traffic-policy
  #
  # More info:
  #   https://ngrok.com/docs/http/traffic-policy/
  #   https://ngrok.com/docs/tls/traffic-policy/
  #   https://ngrok.com/docs/tcp/traffic-policy/

  # - name: example-traffic-policy
  #   description: example traffic policy
  #   metadata: it's a traffic policy!
  #   url: myapp.ngrok.app
  #   traffic_policy:
  #     inbound:
  #        - actions:
  #          - type: custom-response
  #            config:
  #              status_code: 200
  #              content: hello, traffic policy!
  #              headers:
  #                content-type: text/plain
  #   upstream:
  #     url: 8080
  #     protocol: http1

  # --------------------------------------------------------------------
  # | SSH Access Endpoint                                              |
  # --------------------------------------------------------------------

  # Endpoint for SSH access.
  #
  # Start with:
  #   ngrok start example-ssh-access

  # - name: example-ssh-access
  #   url: "tcp://1.tcp.ngrok.io:12345"
  #   upstream:
  #     url: 22
  #     protocol: tcp
