### ISSUE TITLE
Connection requests fails [error 101] NETWORK IS UNREACHABLE 

### ISSUE THREAD

**Issue by shashankfzb** [ultrasecurity/Storm-Breaker#300]
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 174, in _new_conn
conn = connection.create_connection(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 96, in create_connection
raise err
File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 86, in create_connection
sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 704, in urlopen
httplib_response = self._make_request(
^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
self._validate_conn(conn)
File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1045, in _validate_conn
conn.connect()
File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 358, in connect
self.sock = conn = self._new_conn()
^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 186, in _new_conn
raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f3249e00cd0>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/requests/adapters.py", line 486, in send
resp = conn.urlopen(
^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 788, in urlopen
retries = retries.increment(
^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 592, in increment
raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /ultrasecurity/Storm-Breaker/main/Settings.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3249e00cd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/maira28/Storm-Breaker/st.py", line 6, in
check.check_update()
File "/home/maira28/Storm-Breaker/modules/check.py", line 36, in check_update
http = requests.get("https://raw.githubusercontent.com/ultrasecurity/Storm-Breaker/main/Settings.json").text
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/requests/api.py", line 73, in get
return request("get", url, params=params, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/requests/api.py", line 59, in request
return session.request(method=method, url=url, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/requests/sessions.py", line 589, in request
resp = self.send(prep, **send_kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/requests/sessions.py", line 703, in send
r = adapter.send(request, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/requests/adapters.py", line 519, in send
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /ultrasecurity/Storm-Breaker/main/Settings.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3249e00cd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

**Comment by JiXia830** [comment]
I am meeting this problem, have you ever solved it?

**Comment by shashankfzb** [comment]
I tried but not able to solve it. Do you ?

**Comment by JiXia830** [comment]
????????
***@***.***



&nbsp;
me too,i am looking for other solutions.


------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "ultrasecurity/Storm-Breaker"                                                                                    ***@***.***&gt;;
Date:&nbsp;Wed, Nov 22, 2023 11:38 PM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:&nbsp;Re: [ultrasecurity/Storm-Breaker] Connection requests fails [error 101] NETWORK IS UNREACHABLE  (Issue #300)





 
I tried but not able to solve it. Do you ?

**Comment by shashankfzb** [comment]
Let me know also, If you get any....

**Comment by JiXia830** [comment]
@joshkar Hi, I solve this problem this morning. I check sh file， find the "model_name_or_path" didn't Set to my Local path, after setting, problem solved.

**Comment by Lukas19122941** [comment]
> @joshkar Hi, I solve this problem this morning. I check sh file， find the "model_name_or_path" didn't Set to my Local path, after setting, problem solved.

I am new to hacking can you make a quic tutorial on it

**Comment by Lukas19122941** [comment]
Btw i am on termux

**Comment by shashankfzb** [comment]
> @joshkar Hi, I solve this problem this morning. I check sh file， find the "model_name_or_path" didn't Set to my Local path, after setting, problem solved.

I tried, but didn't find any "model_name_or_path" in my install.sh file. can you please ellaborate more

**Comment by shashankfzb** [comment]
I've got the solution, actually github raw website is not responding so I've commented out the line in st.py file and now it's working.
