### ISSUE TITLE
am on Parrot Os  and got this error

### ISSUE THREAD

**Issue by githiakalaban** [ultrasecurity/Storm-Breaker#39]
installed in  /opt directory
Traceback (most recent call last):
  File "/opt/Storm-Breaker/Storm-Breaker.py", line 7, in <module>
    from modules import localhost
  File "/opt/Storm-Breaker/modules/localhost.py", line 1, in <module>
    from pyngrok import ngrok
ModuleNotFoundError: No module named 'pyngrok'

**Comment by bennetho** [comment]
Use $sudo pip3 install pyngrok
