### ISSUE TITLE
Error: NGROK Download Not Complete 

### ISSUE THREAD

**Issue by W-3B** [ultrasecurity/Storm-Breaker#4]
t=2020-12-20T00:51:42-0500 lvl=eror msg="failed to reconnect session" obj=csess id=5bc7c15dc406 err="read tcp 192.168.79.129:52768->3.133.228.214:443: read: connection reset by peer"                                                                                                                                                      
Traceback (most recent call last):                                                                                                                                    
  File "Storm-Breaker.py", line 36, in <module>                                                                                                                       
    localhost.screen()                                                                                                                                                
  File "/root/Downloads/Storm-Breaker/modules/localhost.py", line 924, in screen                                                                                      
    a = ngrok.connect(4387,"http",auth_token=token)                                                                                                                   
  File "/usr/local/lib/python3.7/dist-packages/pyngrok/ngrok.py", line 245, in connect                                                                                
    api_url = get_ngrok_process(pyngrok_config).api_url                                                                                                               
  File "/usr/local/lib/python3.7/dist-packages/pyngrok/ngrok.py", line 162, in get_ngrok_process                                                                      
    return process.get_process(pyngrok_config)                                                                                                                        
  File "/usr/local/lib/python3.7/dist-packages/pyngrok/process.py", line 295, in get_process                                                                          
    return _start_process(pyngrok_config)                                                                                                                             
  File "/usr/local/lib/python3.7/dist-packages/pyngrok/process.py", line 465, in _start_process                                                                       
    ngrok_process.startup_error)                                                                                                                                      
pyngrok.exception.PyngrokNgrokError: The ngrok process errored on start: read tcp 192.168.79.129:52768->3.133.228.214:443: read: connection reset by peer.

**Comment by PRINCEBEN900** [comment]
I've Got Same Issue😔
