### ISSUE TITLE
ngrok error?

### ISSUE THREAD

**Issue by Davizun** [ultrasecurity/Storm-Breaker#47]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/installer.py", line 94, in install_ngrok
    download_path = _download_file(url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/installer.py", line 232, in _download_file
    with open(download_path, "wb") as f:
PermissionError: [Errno 13] Permission denied: '/tmp/ngrok-stable-linux-amd64.zip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Storm-Breaker.py", line 50, in <module>
    localhost.micro()
  File "/home/davi/Storm-Breaker/modules/localhost.py", line 152, in micro
    a = ngrok.connect(6565,"http",auth_token=token)
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 251, in connect
    api_url = get_ngrok_process(pyngrok_config).api_url
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 160, in get_ngrok_process
    install_ngrok(pyngrok_config)
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 98, in install_ngrok
    installer.install_ngrok(pyngrok_config.ngrok_path)
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/installer.py", line 98, in install_ngrok
    raise PyngrokNgrokInstallError("An error occurred while downloading ngrok from {}: {}".format(url, e))
pyngrok.exception.PyngrokNgrokInstallError: An error occurred while downloading ngrok from https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip: [Errno 13] Permission denied: '/tmp/ngrok-stable-linux-amd64.zip'

```

yeah i use XUbuntu 20.04 and this error shows up when i make an action

**Comment by Joshsticko** [comment]
Got the same thing, not sure how to fix it. I was able to reproduce the error by using `sudo ngrok` which produced the "downloading ngrok..." message followed by the error described above. Not sure if this is of much use. If `ngrok` is run without sudo permissions, it seems to work fine.

**Comment by pmchohan** [comment]
tried uninstalling ngrok first, then change directory to tmp/
and remove the ngrok achieve:
sudo rm ngrok-stable-linux-amd64.zip
but got a new error while running stormbreaker 🙃
![Screenshot_20220322_100823](https://user-images.githubusercontent.com/102051545/159412089-91f25b3f-8f24-49ed-b580-e9c48da5728a.png)
