### ISSUE TITLE
ModuleNotFoundError: No module named 'pyngrok'

### ISSUE THREAD

**Issue by ashishmishra-bit** [ultrasecurity/Storm-Breaker#48]
Traceback (most recent call last):
  File "Storm-Breaker.py", line 7, in <module>
    from modules import localhost
  File "/home/ashish/Desktop/Storm-Breaker/modules/localhost.py", line 1, in <module>
    from pyngrok import ngrok
ModuleNotFoundError: No module named 'pyngrok'

**Comment by CoreResponsive** [comment]
I have this same error

**Comment by dirtbag145** [comment]
Had this issue too, but I ran everything in root, had removed also any PPA like deadsnake

**Comment by stevengreg2020** [comment]
─(root💀kali)-[/home/nexphisher/Storm-Breaker]
└─# python3 Storm-Breaker.py
Traceback (most recent call last):
  File "/home/nexphisher/Storm-Breaker/Storm-Breaker.py", line 7, in <module>
    from modules import localhost
  File "/home/nexphisher/Storm-Breaker/modules/localhost.py", line 1, in <module>
    from pyngrok import ngrok
ModuleNotFoundError: No module named 'pyngrok'


is there no solution to this error yet.????

**Comment by hidog123** [comment]
hey guys the solution is very simple 
**sudo pip3 install -r requirments.txt**

**Comment by JustinH71** [comment]
pip3 install pyngrok
