### ISSUE TITLE
ngrok

### ISSUE THREAD

**Issue by Strannik74** [ultrasecurity/Storm-Breaker#5]
Hello!
Error
Traceback (most recent call last):
  File "/root/Storm-Breaker/Storm-Breaker.py", line 42, in <module>
    localhost.location()
  File "/root/Storm-Breaker/modules/localhost.py", line 327, in location
    a = ngrok.connect(8767,"http",auth_token=token)
  File "/usr/local/lib/python3.9/dist-packages/pyngrok/ngrok.py", line 183, in connect
    api_url = get_ngrok_process(ngrok_path, config_path, auth_token, region).api_url
  File "/usr/local/lib/python3.9/dist-packages/pyngrok/ngrok.py", line 135, in get_ngrok_process
    return process.get_process(ngrok_path, config_path, auth_token, region)
  File "/usr/local/lib/python3.9/dist-packages/pyngrok/process.py", line 147, in get_process
    return _start_process(ngrok_path, config_path, auth_token, region)
  File "/usr/local/lib/python3.9/dist-packages/pyngrok/process.py", line 270, in _start_process
    raise PyngrokNgrokError("The ngrok process errored on start.", ngrok_process.startup_logs,
pyngrok.exception.PyngrokNgrokError: The ngrok process errored on start.

**Comment by manav533** [comment]
?

**Comment by danya2001** [comment]
I have the same fucking issue

**Comment by baobaopips** [comment]
me 2 how to fix it

**Comment by p7veasna** [comment]
Problem with ngrok.io register
