### ISSUE TITLE
unknown error

### ISSUE THREAD

**Issue by cyberhecker** [ultrasecurity/Storm-Breaker#58]
t=2021-09-24T23:20:55-0400 lvl=eror msg="failed to auth" obj=tunnels.session err="The authtoken you specified does not look like a proper ngrok tunnel authtoken.\nYour authtoken: 1yaP1QLD0cVVKBknmtX9TAduxr6_6BSaEj1DVgGXFiVSHZbz9~\nInstructions to install your authtoken are on your ngrok dashboard:\nhttps://dashboard.ngrok.com/get-started/your-authtoken\r\n\r\nERR_NGROK_105\r\n"                                                                                                                            
t=2021-09-24T23:20:55-0400 lvl=eror msg="failed to reconnect session" obj=csess id=2cfdcaa56b9f err="The authtoken you specified does not look like a proper ngrok tunnel authtoken.\nYour authtoken: 1yaP1QLD0cVVKBknmtX9TAduxr6_6BSaEj1DVgGXFiVSHZbz9~\nInstructions to install your authtoken are on your ngrok dashboard:\nhttps://dashboard.ngrok.com/get-started/your-authtoken\r\n\r\nERR_NGROK_105\r\n"                                                                                                         
t=2021-09-24T23:20:55-0400 lvl=eror msg="session closing" obj=tunnels.session err="The authtoken you specified does not look like a proper ngrok tunnel authtoken.\nYour authtoken: 1yaP1QLD0cVVKBknmtX9TAduxr6_6BSaEj1DVgGXFiVSHZbz9~\nInstructions to install your authtoken are on your ngrok dashboard:\nhttps://dashboard.ngrok.com/get-started/your-authtoken\r\n\r\nERR_NGROK_105\r\n"                                                                                                                           
Traceback (most recent call last):                                                                                                                                      
  File "/home/kali/Storm-Breaker/Storm-Breaker.py", line 46, in <module>                                                                                                
    localhost.webcham()                                                                                                                                                 
  File "/home/kali/Storm-Breaker/modules/localhost.py", line 74, in webcham                                                                                             
    a = ngrok.connect(4545,"http",auth_token=token)
  File "/usr/local/lib/python3.9/dist-packages/pyngrok/ngrok.py", line 251, in connect
    api_url = get_ngrok_process(pyngrok_config).api_url
  File "/usr/local/lib/python3.9/dist-packages/pyngrok/ngrok.py", line 162, in get_ngrok_process
    return process.get_process(pyngrok_config)
  File "/usr/local/lib/python3.9/dist-packages/pyngrok/process.py", line 295, in get_process
    return _start_process(pyngrok_config)
  File "/usr/local/lib/python3.9/dist-packages/pyngrok/process.py", line 464, in _start_process
    raise PyngrokNgrokError("The ngrok process errored on start: {}.".format(ngrok_process.startup_error),
pyngrok.exception.PyngrokNgrokError: The ngrok process errored on start: The authtoken you specified does not look like a proper ngrok tunnel authtoken.\nYour authtoken: 1yaP1QLD0cVVKBknmtX9TAduxr6_6BSaEj1DVgGXFiVSHZbz9~\nInstructions to install your authtoken are on your ngrok dashboard:\nhttps://dashboard.ngrok.com/get-started/your-authtoken\r\n\r\nERR_NGROK_105\r\n.

**Comment by cyberhecker** [comment]
plz help 
i am new to using this software but plz help me
